# 01 - Kontrola jakości danych

## Cel:

Sprawdzenie braków, anomalii oraz wartości fizycznie niemożliwych w surowych danych meterologicznych i poziomu wody

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
import os
os.chdir('..')
print("Aktualny folder:", os.getcwd())

from src.data.dataset import build_meteo_dataframe, build_water_level_dataframe

Aktualny folder: /Users/majamarkiewicz/PycharmProjects/PortCanals

## Wczytywanie surowych danych meterologicznych

In [2]:
df_meteo_raw = build_meteo_dataframe()
print("Kształt danych:", df_meteo_raw.shape)
df_meteo_raw.head()

Kształt danych: (43680, 5)

               Data Opad [mm] Temperatura [C] Wilgotność [%] Ciśnienie [hPa]
0  2025-07-01 00:00         0            14.8             76          1016.2
1  2025-07-01 01:00         0            14.6           74.2          1016.3
2  2025-07-01 02:00         0            14.9           67.8          1016.2
3  2025-07-01 03:00         0            14.9           64.1          1016.4
4  2025-07-01 04:00         0              15           59.4          1016.5

In [3]:
df_meteo_raw.tail()

,Data,Opad [mm],Temperatura [C],Wilgotność [%],Ciśnienie [hPa]
4412,2021-12-31 19:00,0,9.4,87.5,1002.5
4413,2021-12-31 20:00,0,8.9,88.4,1003.4
4414,2021-12-31 21:00,0,8.4,88.3,1004
4415,2021-12-31 22:00,0,8.1,86.7,1004.4
4416,2021-12-31 23:00,0,8,87.2,1004.8

In [4]:
df_meteo_raw.info()

<class 'pandas.DataFrame'>
Index: 43680 entries, 0 to 4416
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data             43680 non-null  str
 1   Opad [mm]        43680 non-null  object
 2   Temperatura [C]  43680 non-null  object
 3   Wilgotność [%]   43680 non-null  object
 4   Ciśnienie [hPa]  43680 non-null  object
dtypes: object(4), str(1)
memory usage: 2.0+ MB

In [5]:
df_meteo_raw.describe()

,Data,Opad [mm],Temperatura [C],Wilgotność [%],Ciśnienie [hPa]
count,43680,43680,43680,43680,43680
unique,43675,396,507,796,708
top,2025-10-26 02:00,0,-,-,-
freq,2,40048,433,433,433

## Wczytywanie surowych danych poziomu wody

In [6]:
df_water_level_raw = build_water_level_dataframe()
print("Kształt danych:", df_water_level_raw.shape)
df_water_level_raw.head()

Kształt danych: (43672, 2)

               Data Poziom wody [m]
0  2025-07-01 00:00            0.34
1  2025-07-01 01:00            0.32
2  2025-07-01 02:00            0.33
3  2025-07-01 03:00            0.32
4  2025-07-01 04:00            0.32

In [7]:
df_water_level_raw.tail()

                  Data Poziom wody [m]
4412  2021-12-31 19:00            0.05
4413  2021-12-31 20:00            0.08
4414  2021-12-31 21:00            0.01
4415  2021-12-31 22:00            0.05
4416  2021-12-31 23:00            0.09

In [8]:
df_water_level_raw.info()

<class 'pandas.DataFrame'>
Index: 43672 entries, 0 to 4416
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data             43672 non-null  str
 1   Poziom wody [m]  43672 non-null  object
dtypes: object(1), str(1)
memory usage: 1023.6+ KB

In [9]:
df_water_level_raw.describe()

                    Data  Poziom wody [m]
count              43672         43672.00
unique             43667           171.00
top     2025-10-26 02:00             0.14
freq                   2          1201.00

## Wnioski i Obserwacje dotyczące surowych danych

### Dane meteorologiczne

- Dane mają **43 680 wierszy** w kroku godzinowym
- Występuje **5 kolumn**, Data, Opad, Temperature, Wilgotność, Ciśnienie
- Daty pochodzą z zakresu 2021-2025
- Kolumny będzie trzeba poddać konwersji (object -> liczby)

### Dane poziomu wody

- Dane mają **43 672 wierszy** w kroku godzinowym
- Daty pochodzą także z zakresu 2021-2025
- Kolumne będzie trzeba poddać konwersji (object -> liczby)

### Dalsze Decyzje

- Dane będą czyszczone przez usunięcie fizycznie nie możliwych wartości
- Nastąpi agregacja do kroku dobowego
- Braki zostaną uzupełnione medianą sezonową